name: Build Markdown with Citations

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install pandoc -y

      - name: Convert Markdown to HTML
        run: |
          mkdir -p output
          for file in *.md; do
            pandoc "$file" --citeproc --bibliography=references.bib -o "output/${file%.md}.html"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
